import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const Terms = () => (
  <div className="min-h-screen">
    <Navbar />
    <main className="pt-32 pb-20 px-6">
      <div className="max-w-3xl mx-auto prose-sm">
        <p className="text-xs tracking-[0.3em] uppercase text-muted-foreground mb-3 font-body font-light">Legal</p>
        <h1 className="text-3xl md:text-5xl font-extralight mb-10 tracking-tight">Terms of Service</h1>

        <div className="space-y-6 text-muted-foreground font-body font-light text-sm leading-relaxed">
          <p><strong className="text-foreground">Last Updated:</strong> April 1, 2026</p>

          <p className="uppercase font-medium text-foreground">PLEASE READ THESE TERMS OF SERVICE CAREFULLY BEFORE ACCESSING OR USING OUR SITE. By registering for and/or accessing and using the Site or Services, you agree to be bound by these Terms of Service and all other terms and policies that appear on the Site or Services. YOU MAY NOT ACCESS OR USE THE SERVICES OR ACCEPT THESE TERMS OF SERVICE IF YOU ARE NOT AT LEAST 18 YEARS OF AGE. IF YOU DO NOT AGREE WITH ALL OF THE PROVISIONS OF THESE TERMS OF SERVICE, DO NOT ACCESS AND/OR USE THE SERVICES.</p>

          <p className="uppercase font-medium text-foreground">ARBITRATION NOTICE: Except for certain kinds of disputes described in Section 12, you agree that disputes arising under these Terms will be resolved by binding, individual arbitration, and BY ACCEPTING THESE TERMS, YOU AND PREMIER VITALITY AND WELLNESS LLC ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN ANY CLASS ACTION OR REPRESENTATIVE PROCEEDING. YOU AGREE TO GIVE UP YOUR RIGHT TO GO TO COURT to assert or defend your rights under this contract (except for matters that may be taken to small claims court). Your rights will be determined by a NEUTRAL ARBITRATOR and NOT a judge or jury.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">1. Overview</h2>
          <p>Premier Vitality and Wellness LLC ("Premier Vitality and Wellness LLC," "we," "us," or "our") owns and operates the website located at premiervitalityandwellness.com (the "Site"). Premier Vitality and Wellness LLC offers the Site, including all information and content therewith (collectively, the "Content"), products available for purchase (the "Products") and various services (the "Services") to you, the user, conditioned upon your acceptance of all terms, conditions, policies and notices stated or referenced herein (the "Terms of Service") and compliance with all applicable laws and regulations. Your use of certain features or components of our Site, access to certain Services or your ability to purchase Products may be limited to those users that have registered an account with us.</p>
          <p>Any new features, tools or services which are added to the current Site shall also be subject to these Terms of Service. You can review the most current version of the Terms of Service at any time on this page. We reserve the right to update, change or replace any part of these Terms of Service by posting updates and/or changes to our Site. Any such changes will be effective as of the date of posting. It is your responsibility to check this page periodically for changes. Your continued use of or access to the Site (including the Content) or purchase of any Services or Products following the posting of any changes constitutes your acceptance of those changes.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">2. Services</h2>
          <p>Premier Vitality and Wellness LLC provides physician-directed wellness and optimization services including but not limited to peptide therapy, hormone optimization, biomarker analysis, nutritional counseling, and related medical services. Services are provided both in-person at our Arizona location and via telehealth/telemedicine. Our Services are currently available only to individuals who are at least 18 years of age.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">2a. Prescription Fulfillment Services</h2>
          <p>We may provide access to prescription fulfillment services offered by licensed compounding pharmacies (the "Pharmacies"). You can expect to receive your prescription drugs from one of our partner pharmacies. Premier Vitality and Wellness LLC does not recommend or endorse any specific prescription drug or pharmacy. PREMIER VITALITY AND WELLNESS LLC MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE SUITABILITY, RELIABILITY, OR TIMELINESS OF THE PHARMACIES OR THE PRESCRIPTION PRODUCTS AND IS NOT RESPONSIBLE FOR ANY OF THE SERVICES PROVIDED BY THE PHARMACIES.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">2b. Healthcare Services — In-Person and Telehealth</h2>
          <p>Premier Vitality and Wellness LLC provides physician-directed medical services both in-person and via telehealth. By receiving in-person medical services at Premier Vitality and Wellness LLC, you acknowledge and agree that: (a) You are voluntarily presenting yourself for evaluation, examination, and treatment at our facility located at 1870 W Frye Rd Ste 1, Chandler, AZ 85224. (b) In-person care involves direct physical examination, potential blood draws, injections, and other procedures as determined medically appropriate by your Provider. (c) You have disclosed all relevant medical history, medications, allergies, and conditions to your Provider prior to receiving care. (d) You understand that no guarantee of outcome is made for any treatment or procedure. (e) You consent to the presence of clinical staff necessary to assist in your care. (f) You understand that photography or imaging of treatment areas may be taken for clinical documentation purposes with your verbal consent at time of service.</p>
          <p>For telehealth services, you consent to receive medical services via telemedicine technology including video conferencing, telephone consultation, and secure messaging. You understand that: (a) The same confidentiality laws that apply to in-person care apply to telehealth interactions. (b) You may withdraw consent to telehealth at any time without affecting your right to in-person care. (c) Potential risks include technical interruptions and, in rare circumstances, security breaches. (d) Your Provider may determine that in-person care is required for your specific situation. (e) You are responsible for ensuring a private, secure environment on your end during telehealth consultations.</p>
          <p className="uppercase font-medium text-foreground">IF YOU THINK YOU MAY HAVE A MEDICAL EMERGENCY, CALL YOUR DOCTOR, GO TO THE EMERGENCY DEPARTMENT, OR CALL 911 IMMEDIATELY.</p>
          <p>By accepting these Terms of Service, you acknowledge and agree that the Providers may send you electronic messages containing results, reports, instructions, and/or advice related to your diagnosis and/or treatment. You are responsible for checking and responding to these messages.</p>
          <p className="uppercase">PREMIER VITALITY AND WELLNESS LLC MAKES NO REPRESENTATIONS OR WARRANTIES ABOUT THE ACCURACY, SUITABILITY, RELIABILITY OR TIMELINESS OF THE DIAGNOSIS AND/OR TREATMENT PROVIDED BY THE PROVIDERS.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">3. Products</h2>
          <p>We may offer certain Products, including prescription products, and non-prescription products such as over-the-counter medications, vitamins, dietary supplements, and wellness products. All prices are in U.S. Dollars. All Products are non-refundable.</p>
          <p>You understand and agree that all Products should be used strictly in accordance with their instructions, precautions and guidelines and in accordance with applicable laws. Use of the Content related to a Product is not meant to serve as a substitute for professional medical advice. Please consult with your Provider regarding the use of any Product before using them.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">3a. Prescription Products</h2>
          <p>Certain Products require a valid prescription by a licensed healthcare provider. You may not purchase a Prescription Product unless and until you have completed a consultation with a Provider and such Provider has provided a written prescription. Prescriptions fulfilled by the Pharmacies may not use child-resistant packaging and Prescription Products may not be dispensed in child-resistant containers.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">4. Self-Pay Financial Agreement</h2>
          <p><strong className="text-foreground">INSURANCE NOT ACCEPTED; YOUR RESPONSIBILITY FOR PAYMENT.</strong> I understand and acknowledge that Premier Vitality and Wellness LLC and its Providers are not paid or reimbursed by managed care plans, Medicare, Medicaid or other government health care programs, or other third-party payors. Premier Vitality and Wellness LLC does not accept insurance for such services. I will be billed directly and shall be personally responsible for payment, regardless of whether I am or will be reimbursed by a managed care plan or other third-party payer.</p>
          <p>I agree to make timely payments for all health care, laboratory and pharmacy services that are provided to me. By providing my payment information, I authorize Premier Vitality and Wellness LLC to charge the credit card or other payment method on file for all items and/or services I receive or are scheduled to receive from the Provider, the laboratories and the pharmacies.</p>
          <p>I understand that the cost of services, including labs and medications, are final and not refundable. This is because the cost of treatment is for professional medical services (including any blood draws) which are fully rendered at point of care. Pharmacy rules prohibit the return of medications for reimbursement because medications are packaged for you and cannot be used for another patient. I understand I will not be able to receive refunds for treatments and for medications, even if they are unused. I understand that Premier Vitality and Wellness LLC reserves the right to discontinue service if I am delinquent on any payments.</p>
          <p>Accepted payment methods include credit card, debit card, and ACH bank transfer. Cash payments are not accepted. Appointments cancelled with less than 24 hours notice may be subject to a cancellation fee.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">5. Billing</h2>
          <p>You agree to provide current, complete and accurate purchase and account information for all purchases. You agree to promptly update your account and other information, including your email address and credit card numbers and expiration dates, so that we can complete your transactions and contact you as needed. You will be responsible for any applicable sales, use, duty, customs or other governmental taxes, levies or fees due with respect to your purchase of Products or Services.</p>
          <p>Some of our Products and/or Services may be available on a subscription basis. For these Products and Services, your payment account will be automatically charged as described for that Product or Service. You may cancel a subscription thirty days before the next monthly processing date of your subscription by contacting Premier Vitality and Wellness LLC at admin@premiervitalityandwellness.com with your cancellation request.</p>
          <p>Premier Vitality and Wellness LLC accepts payment from HSA/FSA accounts using credit or debit cards commonly associated with these types of accounts. Premier Vitality and Wellness LLC makes no warranty, expressed or implied, that your payment will be accepted by your HSA/FSA administrator as a valid expense for the account. Premier Vitality and Wellness LLC will provide you with the receipts needed for submission to your account administrator and your Provider will provide a Letter of Medical Necessity if requested.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">6. Your Obligations; Your Representations and Warranties</h2>
          <p>You are solely responsible for maintaining the security of your account and are responsible for all activities that occur under your account. You agree to immediately notify us in writing of any unauthorized use of this Site or any other breaches of security.</p>
          <p>You shall submit only truthful, complete, and accurate information through the Site. You are prohibited from using the Site or its Content: (a) for any unlawful purpose; (b) to solicit others to perform or participate in any unlawful acts; (c) to violate any international, federal, state, or local regulations, rules, laws, or ordinances; (d) to infringe upon or violate our intellectual property rights or the intellectual property rights of others; (e) to harass, abuse, insult, harm, defame, slander, disparage, intimidate, or discriminate based on gender, sexual orientation, religion, ethnicity, race, age, national origin, or disability; (f) to submit false or misleading information; (g) to upload or transmit viruses or any other type of malicious code; (h) to collect or track the personal information of others; (i) to spam, phish, pharm, pretext, spider, crawl, or scrape; (j) for any obscene or immoral purpose; or (k) to interfere with or circumvent the security features of the Site or any related website or the Internet.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">7. Third Parties; Third-Party Links</h2>
          <p>Certain Content, Products and Services available on the Site may include materials from third parties. Premier Vitality and Wellness LLC has no responsibility for the accuracy, suitability or reliability of such third-party Content. Third-party links on the Site may direct you to third-party websites not affiliated with us. We are not responsible for examining or evaluating the content or accuracy of such third-party websites. You understand and agree that we will not be liable for any harm or damages related to the purchase or use of goods, services, resources, or content from any third party.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">8. Intellectual Property</h2>
          <p>Subject to these Terms of Service, you are hereby granted a non-transferable, non-exclusive, limited, revocable license to use the software and access the Content provided to you through the Site. All Content displayed on our Site is the exclusive property of Premier Vitality and Wellness LLC. Except as permitted herein, any use of the Content, including reproduction, modification, distribution, republishing, transmission, display or performance is strictly prohibited.</p>
          <p>You grant Premier Vitality and Wellness LLC a worldwide, perpetual, non-exclusive, irrevocable, royalty-free license to use, reproduce, distribute, modify, adapt, publish, translate, and create derivative works from any content you submit to the Site. Any ideas, suggestions, or feedback you submit to us will be the exclusive property of Premier Vitality and Wellness LLC.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">9. Termination</h2>
          <p>Premier Vitality and Wellness LLC may terminate your access to the Site or any of the Services at any time and for any reason, including your breach of any of the Terms of Service. Upon termination, your access to the Site and the terminated Services will immediately cease but you will remain liable for all amounts due up to and including the date of termination. The disclaimers, limitations of liabilities, releases and waivers set forth in these Terms of Service shall survive any such termination.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">10. Disclaimer of Warranties</h2>
          <p className="uppercase">ALL SERVICES, THE SITE AND CONTENT ARE PROVIDED "AS IS," "AS AVAILABLE," AND "WITH ALL FAULTS." PREMIER VITALITY AND WELLNESS LLC DISCLAIMS ALL WARRANTIES AND CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, DURABILITY, TITLE, OR NON-INFRINGEMENT. PREMIER VITALITY AND WELLNESS LLC DOES NOT WARRANT OR GUARANTEE THAT THE CONTENT, PRODUCTS, SERVICES OR THE SITE ARE OR WILL BE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE.</p>
          <p className="uppercase">YOU AGREE THAT WHEN YOU VIEW, DOWNLOAD OR OTHERWISE OBTAIN CONTENT FROM OR THROUGH THE SITE, OR BY USING THE SERVICES OR A PRODUCT, YOU DO SO AT YOUR OWN RISK.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">11. Limitation of Liability</h2>
          <p className="uppercase">PREMIER VITALITY AND WELLNESS LLC, INCLUDING ITS OFFICERS, DIRECTORS, EMPLOYEES, AGENTS OR REPRESENTATIVES (COLLECTIVELY, THE "PREMIER VITALITY AND WELLNESS LLC PARTIES") WILL NOT BE LIABLE FOR ANY DAMAGES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH THE USE OF THE SITE, THE CONTENT, OR ANY OF THE SERVICES OR PRODUCTS. TO THE FULLEST EXTENT PERMITTED BY LAW, THE PREMIER VITALITY AND WELLNESS LLC PARTIES SHALL NOT HAVE ANY LIABILITY FOR ANY INDIRECT, SPECIAL, EXEMPLARY, INCIDENTAL OR CONSEQUENTIAL DAMAGES, INCLUDING DAMAGES FOR LOSS OF PROFITS, USE, DATA OR OTHER INTANGIBLES. THE PREMIER VITALITY AND WELLNESS LLC PARTIES' LIABILITY SHALL NOT EXCEED THE AMOUNT YOU HAVE PAID FOR PRODUCTS AND SERVICES IN THE SIX (6) MONTHS PRECEDING THE DATE OF THE EVENT THAT IS THE BASIS FOR THE CLAIM.</p>
          <p className="uppercase">YOU AGREE THAT YOU MUST BRING ANY CLAIMS ARISING IN CONNECTION WITH YOUR USE OF THE SITE OR CONTENT WITHIN ONE (1) YEAR OF THE DATE OF THE EVENT GIVING RISE TO SUCH ACTION.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">12. Indemnification</h2>
          <p>You agree to indemnify, defend and hold harmless the Premier Vitality and Wellness LLC Parties, and the Pharmacies and Providers, from any and all third party suits, actions, claims, proceedings, damages, settlements, judgments, injuries, liabilities, obligations, losses, risks, costs, and expenses (including, without limitation, attorneys' fees and litigation expenses) relating to or arising from your use of the Site, or your breach of these Terms of Service, or your violation of any law or the rights of a third party.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">13. Dispute Resolution and Arbitration</h2>
          <p><strong className="text-foreground">13a. Generally.</strong> In the interest of resolving disputes between you and Premier Vitality and Wellness LLC in the most expedient and cost effective manner, and except as described in Section 13b, you and Premier Vitality and Wellness LLC agree that every dispute arising in connection with these terms will be resolved by binding arbitration. Arbitration is less formal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, may allow for more limited discovery than in court, and can be subject to very limited review by courts. Arbitrators can award the same damages and relief that a court can award. This agreement to arbitrate disputes includes all claims arising out of or relating to any aspect of these terms, whether based in contract, tort, statute, fraud, misrepresentation, or any other legal theory, and regardless of whether a claim arises during or after the termination of these terms. YOU AND PREMIER VITALITY AND WELLNESS LLC ARE EACH WAIVING THE RIGHT TO A TRIAL BY JURY OR TO PARTICIPATE IN A CLASS ACTION.</p>
          <p><strong className="text-foreground">13b. Exceptions.</strong> Nothing in these terms will be deemed to waive, preclude, or otherwise limit the right of either party to: (a) bring an individual action in small claims court; (b) pursue an enforcement action through the applicable federal, state, or local agency if that action is available; (c) seek injunctive relief in a court of law in aid of arbitration; or (d) file suit in a court of law to address an intellectual property infringement claim.</p>
          <p><strong className="text-foreground">13c. Arbitrator.</strong> Any arbitration between you and Premier Vitality and Wellness LLC will be settled under the Federal Arbitration Act and administered by the American Arbitration Association ("AAA") under its Consumer Arbitration Rules (collectively, "AAA Rules") as modified by these terms. The arbitration will be before a single arbitrator. The AAA rules and filing forms are available online at www.adr.org, by calling the AAA at 1-800-778-7879, or by contacting Premier Vitality and Wellness LLC. The arbitrator has exclusive authority to resolve any dispute relating to the interpretation, applicability, or enforceability of this binding arbitration agreement.</p>
          <p><strong className="text-foreground">13d. Notice of Arbitration; Process.</strong> A party who intends to seek arbitration must first send a written notice of the dispute to the other party by certified U.S. Mail or by Federal Express (signature required) or, only if that other party has not provided a current physical address, then by electronic mail ("Notice of Arbitration"). Premier Vitality and Wellness LLC's address for Notice is: 1870 W Frye Rd Ste 1, Chandler, AZ 85224. The Notice of Arbitration must: (a) describe the nature and basis of the claim or dispute; and (b) set forth the specific relief sought ("Demand"). The parties will make good faith efforts to resolve the claim directly, but if the parties do not reach an agreement to do so within 30 days after the Notice of Arbitration is received, you or Premier Vitality and Wellness LLC may commence an arbitration proceeding. All arbitration proceedings between the parties will be confidential unless otherwise agreed by the parties in writing.</p>
          <p><strong className="text-foreground">13e. Fees.</strong> If you commence arbitration in accordance with these Terms, Premier Vitality and Wellness LLC will reimburse you for your payment of the filing fee, unless your claim is for more than US$10,000, in which case the payment of any fees will be decided by the AAA Rules. Any arbitration hearing will take place at a location to be agreed upon in Maricopa County, Arizona, but if the claim is for US$10,000 or less, you may choose whether the arbitration will be conducted: (a) solely on the basis of documents submitted to the arbitrator; (b) through a non-appearance based telephone hearing; or (c) by an in-person hearing in Maricopa County, Arizona.</p>
          <p><strong className="text-foreground">13f. No Class Actions.</strong> YOU AND PREMIER VITALITY AND WELLNESS LLC AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, unless both you and Premier Vitality and Wellness LLC agree otherwise, the arbitrator may not consolidate more than one person's claims, and may not otherwise preside over any form of a representative or class proceeding.</p>
          <p><strong className="text-foreground">13g. Enforceability.</strong> If Section 13f or the entirety of this Section 13 is found to be unenforceable, then the entirety of this Section 13 will be null and void and, in that case, the exclusive jurisdiction and venue described in Section 14 will govern any action arising out of or related to these terms.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">14. Governing Law</h2>
          <p>These Terms of Service shall be governed by and construed in accordance with the laws of the State of Arizona.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">15. Privacy Policy</h2>
          <p>Premier Vitality and Wellness LLC respects your privacy. Please review our <a href="/privacy" className="underline text-foreground hover:text-primary transition-colors">Privacy Policy</a> for information regarding how we may collect, use and disclose your personal information. The Privacy Policy is hereby incorporated by reference into these Terms of Service.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">16. Electronic Communications</h2>
          <p>In connection with your access or use of the Services, you hereby consent to receive electronic communications from us, the Providers and the Pharmacies, whether through email, through the Site, or other electronic means. You hereby agree that such electronic communications will satisfy any legal requirement that such communications be in writing.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">17. General Terms</h2>
          <p>The headings used in this agreement are included for convenience only and will not limit or otherwise affect these Terms of Service. In the event that any provision of these Terms of Service is determined to be unlawful, void or unenforceable, such provision shall nonetheless be enforceable to the fullest extent permitted by applicable law, and the unenforceable portion shall be deemed to be severed from these Terms of Service. The failure of us to exercise or enforce any right or provision of these Terms of Service shall not constitute a waiver of such right or provision. These Terms of Service shall not create any partnership, joint venture, employment, or other agency relationship between you and Premier Vitality and Wellness LLC. Premier Vitality and Wellness LLC may transfer its contractual rights and obligations set forth in these Terms of Service to any affiliate or to another third party in the event that some or all of Premier Vitality and Wellness LLC's business is transferred to a third party by way of merger, sale of its assets or otherwise. You may not assign any of your rights hereunder.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">18. Digital Millennium Copyright Act</h2>
          <p>If you are a copyright owner or an agent thereof and believe that any content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act ("DMCA") by providing us with the following information in writing: (a) a physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; (b) identification of the copyrighted work claimed to have been infringed; (c) identification of the material that is claimed to be infringing and information reasonably sufficient to permit Premier Vitality and Wellness LLC to locate the material; (d) information reasonably sufficient to permit Premier Vitality and Wellness LLC to contact you, such as an address, telephone number, and email; (e) a statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and (f) a statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. You may direct copyright infringement notifications to us at admin@premiervitalityandwellness.com.</p>

          <h2 className="text-lg font-extralight text-foreground pt-4">19. Contact Information</h2>
          <p>Questions about the Terms of Service should be sent to:</p>
          <p>Premier Vitality and Wellness LLC<br />
          1870 W Frye Rd Ste 1<br />
          Chandler, AZ 85224<br />
          Phone: (480) 234-9108<br />
          Email: admin@premiervitalityandwellness.com</p>
        </div>
      </div>
    </main>
    <Footer />
  </div>
);

export default Terms;
